name: segdev

services:
  app:
    extends:
      file: compose.yml
      service: base-app
    build:
      args:
        RAILS_ENV: test
    env_file:
      - ../.env.test

  db:
    extends:
      file: compose.yml
      service: base-db
    env_file:
      - ../.env.test

volumes:
  db_data:
  db_socket:
  storage:

secrets:
  postgres_user:
    file: secrets/test/postgres_user
  postgres_password:
    file: secrets/test/postgres_password
  rails_credentials:
    file: ../config/credentials/test.yml.enc
  rails_master_key:
    file: ../config/credentials/test.key