name: segdev

services:
  app:
    extends:
      file: compose.yml
      service: base-app
    build:
      args:
        RAILS_ENV: development
    env_file:
      - ../.env.development
    ports:
      - 3000:3000

  db:
    extends:
      file: compose.yml
      service: base-db
    env_file:
      - ../.env.development
    volumes:
      # - /var/run/postgresql:/var/run/postgresql # uncomment to make service available locally
    ports:
      - 5432:5432

volumes:
  db_data:
  db_socket:
  storage:

secrets:
  postgres_user:
    file: secrets/development/postgres_user
  postgres_password:
    file: secrets/development/postgres_password
  rails_credentials:
    file: ../config/credentials/development.yml.enc
  rails_master_key:
    file: ../config/credentials/development.key