name: segdev

services:
  base-app:
    build:
      context: ..
      secrets:
        - rails_credentials
        - rails_master_key
      args:
        RUBY_VERSION: 3.3.3
    image: segdev:latest
    volumes:
      # - ..:/rails # uncomment to mount local files into the container, making them live
      - db_socket:/var/run/postgresql:z
      - storage:/rails/storage:Z
    secrets:
      - rails_credentials
      - rails_master_key
    depends_on:
      - db
  
  base-db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data:Z
      - db_socket:/var/run/postgresql:z
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
