name: segdev

services:
  app:
    extends:
      file: compose.yml
      service: base-app
    build:
      args:
        RAILS_ENV: development
    env_file:
      - ../.env.development
    volumes:
      - ..:/rails
    ports:
      - 3000:3000

  db:
    extends:
      file: compose.yml
      service: base-db
    env_file:
      - ../.env.development
    volumes:
      # - /var/run/mysqld:/var/run/mysqld # uncomment to make service available locally
      - ./init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

volumes:
  db_data:
  db_socket:
  storage:

secrets:
  mysql_password:
    file: secrets/development/mysql_password
  mysql_root_password:
    file: secrets/development/mysql_root_password
  mysql_user:
    file: secrets/development/mysql_user
  rails_credentials:
    file: ../config/credentials/development.yml.enc
  rails_master_key:
    file: ../config/credentials/development.key