# frozen_string_literal: true

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>

development:
  <<: *default
  database: segdev_development

test:
  <<: *default
  database: segdev_test

production:
  <<: *default
  database: segdev_production
